export const projects = [
  {
    title: '#Bored',
    description: "Made for GMTK 2025, this project had less work done by me, since I was on vacation.",
    image: '/images/Bored.png',
    tags: ['Game Jam', 'Prototype', 'Unity', 'C#'],
    source: 'https://alimad.itch.io/gmtk25',
    visit: 'https://alimad.itch.io/gmtk25',
    playtitle: 'Play the game',
    extratitle: 'No code available yet',
    id: 0,
  },
  {
    title: 'Gleam Box',
    description: "This project didn't have much contribution from me, but I am still marked as contributor.",
    image: '/images/Gleam.png',
    tags: ['Game Jam', 'Unity', 'C#'],
    source: 'https://alimad.itch.io/gleambox',
    visit: 'https://alimad.itch.io/gleambox',
    playtitle: 'Play the game',
    extratitle: 'No code available yet',
    id: 1,
  },
  {
    title: 'Cube Madness',
    description: "A relatively small puzzle game, made entirely by me.",
    image: '/images/Cube.png',
    tags: ['Unity', 'C#', 'Puzzle'],
    source: 'https://github.com/F1nndegamer/Cube-Madness',
    visit: 'https://play.google.com/store/apps/details?id=com.f1nndegamer.cubemadness',
    playtitle: 'Find it on google play!',
    id: 2,
  },
  {
    title: 'Magnet Madness',
    description: "A refined version of a previous project, published on Google Play.",
    image: '/images/Magnet.png',
    tags: ['Unity', 'C#', 'Mobile Game'],
    source: 'https://github.com/F1nndegamer/MagnetMadness',
    visit: 'https://play.google.com/store/apps/details?id=com.F1nndegamer.MagnetMadness',
    playtitle: 'Find it on google play!',
    id: 3,
  },
  {
    title: 'Timber Trials',
    description: "A game made with 5 people, balancing work with school and a somewhat ambitious idea.",
    image: '/images/Lumber.png',
    tags: ['Unity', 'C#', 'Team Project', 'Game Jam'],
    source: 'https://github.com/F1nndegamer/TimberTrials',
    visit: 'https://f1nndegamer.itch.io/jacklumber',
    playtitle: 'Play the game',
    id: 4,
  },
  {
    title: 'Please Suggest a Name',
    description: "Made in 74 hours for Winter Melon Jam 24 with a different team. Very fun project.",
    image: '/images/Magnet.png',
    tags: ['Unity', 'C#', 'Game Jam', 'Team Project'],
    source: 'https://github.com/F1nndegamer/MagnetMadness',
    visit: 'https://alimad.itch.io/wmj24',
    playtitle: 'Play the game',
    id: 5,
  },
  {
    title: 'Window Walker',
    description: "Led a team of 8 people in 4 days for GMTK Game Jam 2024.",
    image: '/images/Window.png',
    tags: ['Unity', 'C#', 'Team Leader', 'Game Jam'],
    source: 'https://github.com/F1nndegamer/Window-Walker',
    visit: 'https://f1nndegamer.itch.io/window-walker',
    playtitle: 'Play the game',
    id: 6,
  },
  {
    title: "Fisherman's Storm",
    description: "Team leader for the Brackeys Jam with a similar team setup.",
    image: '/images/Storm.png',
    tags: ['Unity', 'C#', 'Team Leader', 'Game Jam'],
    source: 'https://github.com/F1nndegamer/Fisherman-s-Storm',
    visit: 'https://ramixang.itch.io/fishermans-storm',
    playtitle: 'Play the game',
    id: 7,
  },
  {
    title: 'One In Ten Dentist',
    description: "Worked with a Turkish team; overcame timezone and language barriers to make a fun game.",
    image: '/images/Dentist.png',
    tags: ['Unity', 'C#', 'Team Project', 'Game Jam'],
    source: 'https://aslanemre.itch.io/one-in-ten-dentist',
    visit: 'https://aslanemre.itch.io/one-in-ten-dentist',
    playtitle: 'Play the game',
    extratitle: 'No code available yet',
    id: 8,
  },
  {
    title: 'LUNA',
    description: "Info coming soon...",
    image: '',
    tags: ['Unity', 'C#', 'AI', 'Project'],
    source: '#',
    visit: '#',
    playtitle: 'Learn Less',
    id: 9,
  },
  {
    title: 'LoopDrive',
    description: "A wearable USB flash drive designed as a ring with a custom circular connector.",
    image: '',
    tags: ['Hardware', 'USB', 'Design', 'Electronics'],
    source: '#',
    visit: '#',
    playtitle: 'Project Cancelled',
    extratitle: 'Project Cancelled',
    id: 10,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my Unity journey' },
  { year: 2018, text: 'Led small team projects' },
  { year: 2019, text: 'Participated in first Game Jams' },
  { year: 2020, text: 'Published small games on itch.io' },
  { year: 2021, text: 'Developed mobile games and wearable projects' },
  { year: 2024, text: 'Led larger teams for GMTK and Brackeys Jams' },
  { year: 2025, text: 'Worked on AI assistant LUNA and personal projects' },
];
